# Generated by Django 4.0.3 on 2022-03-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradingSystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultyName', models.CharField(max_length=225)),
                ('facultyImage', models.ImageField(upload_to='pics')),
                ('facultyDesc', models.TextField()),
            ],
        ),
    ]
