# Generated by Django 3.2.4 on 2022-04-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GradingSystem', '0002_faculties'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecturerName', models.CharField(max_length=225)),
                ('lecturerCourse', models.CharField(max_length=225)),
                ('courseCode', models.CharField(max_length=225)),
                ('communicationSkills', models.CharField(max_length=225)),
                ('listeningSkills', models.CharField(max_length=225)),
                ('userReview', models.TextField()),
            ],
        ),
    ]
